// Code generated by qtc from "piechart.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line piechart.qtpl:1
package piechart

//line piechart.qtpl:1
import "github.com/grokify/gocharts/v2/charts/google"

//line piechart.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line piechart.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line piechart.qtpl:2
func StreamPieChartMaterialHTML(qw422016 *qt422016.Writer, chart google.Chart) {
//line piechart.qtpl:2
	qw422016.N().S(`
  <div id="`)
//line piechart.qtpl:3
	qw422016.N().S(chart.ChartDivOrDefault())
//line piechart.qtpl:3
	qw422016.N().S(`"></div>
  <script>
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
      var data = google.visualization.arrayToDataTable(`)
//line piechart.qtpl:9
	qw422016.N().Z(chart.DataTableJSON())
//line piechart.qtpl:9
	qw422016.N().S(`);

      var options = `)
//line piechart.qtpl:11
	qw422016.N().Z(chart.OptionsJSON())
//line piechart.qtpl:11
	qw422016.N().S(`

      var chart = new google.visualization.PieChart(document.getElementById('`)
//line piechart.qtpl:13
	qw422016.N().S(chart.ChartDivOrDefault())
//line piechart.qtpl:13
	qw422016.N().S(`'));

      chart.draw(data, options);
    }
    </script>
`)
//line piechart.qtpl:18
}

//line piechart.qtpl:18
func WritePieChartMaterialHTML(qq422016 qtio422016.Writer, chart google.Chart) {
//line piechart.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line piechart.qtpl:18
	StreamPieChartMaterialHTML(qw422016, chart)
//line piechart.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line piechart.qtpl:18
}

//line piechart.qtpl:18
func PieChartMaterialHTML(chart google.Chart) string {
//line piechart.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line piechart.qtpl:18
	WritePieChartMaterialHTML(qb422016, chart)
//line piechart.qtpl:18
	qs422016 := string(qb422016.B)
//line piechart.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line piechart.qtpl:18
	return qs422016
//line piechart.qtpl:18
}
