// Code generated by qtc from "piechart_page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line piechart_page.qtpl:1
package piechart

//line piechart_page.qtpl:1
import "github.com/grokify/gocharts/v2/charts/google"

//line piechart_page.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line piechart_page.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line piechart_page.qtpl:2
func StreamPieChartMaterialHTMLPage(qw422016 *qt422016.Writer, chart google.Chart) {
//line piechart_page.qtpl:2
	qw422016.N().S(`<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
  <h1>`)
//line piechart_page.qtpl:8
	qw422016.N().S(chart.PageTitle())
//line piechart_page.qtpl:8
	qw422016.N().S(`</h1>
  <div id="`)
//line piechart_page.qtpl:9
	qw422016.N().S(chart.ChartDivOrDefault())
//line piechart_page.qtpl:9
	qw422016.N().S(`"></div>
  <script>
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
      var data = google.visualization.arrayToDataTable(`)
//line piechart_page.qtpl:15
	qw422016.N().Z(chart.DataTableJSON())
//line piechart_page.qtpl:15
	qw422016.N().S(`);

      var options = `)
//line piechart_page.qtpl:17
	qw422016.N().Z(chart.OptionsJSON())
//line piechart_page.qtpl:17
	qw422016.N().S(`

      var chart = new google.visualization.PieChart(document.getElementById('`)
//line piechart_page.qtpl:19
	qw422016.N().S(chart.ChartDivOrDefault())
//line piechart_page.qtpl:19
	qw422016.N().S(`'));

      chart.draw(data, options);
    }
    </script>
  </body>
</html>
`)
//line piechart_page.qtpl:26
}

//line piechart_page.qtpl:26
func WritePieChartMaterialHTMLPage(qq422016 qtio422016.Writer, chart google.Chart) {
//line piechart_page.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line piechart_page.qtpl:26
	StreamPieChartMaterialHTMLPage(qw422016, chart)
//line piechart_page.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line piechart_page.qtpl:26
}

//line piechart_page.qtpl:26
func PieChartMaterialHTMLPage(chart google.Chart) string {
//line piechart_page.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line piechart_page.qtpl:26
	WritePieChartMaterialHTMLPage(qb422016, chart)
//line piechart_page.qtpl:26
	qs422016 := string(qb422016.B)
//line piechart_page.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line piechart_page.qtpl:26
	return qs422016
//line piechart_page.qtpl:26
}
