// This file is automatically generated by qtc from "chart_html_simple.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line chart_html_simple.qtpl:1
package c3

//line chart_html_simple.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line chart_html_simple.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line chart_html_simple.qtpl:1
func StreamC3ChartHtmlSimple(qw422016 *qt422016.Writer, id string, chart C3Chart) {
	//line chart_html_simple.qtpl:1
	qw422016.N().S(`
<div id="`)
	//line chart_html_simple.qtpl:2
	qw422016.E().S(id)
	//line chart_html_simple.qtpl:2
	qw422016.N().S(`"></div>
<script>
c3.generate(`)
	//line chart_html_simple.qtpl:4
	qw422016.N().Z(chart.MustJSON())
	//line chart_html_simple.qtpl:4
	qw422016.N().S(`);
</script>
`)
//line chart_html_simple.qtpl:6
}

//line chart_html_simple.qtpl:6
func WriteC3ChartHtmlSimple(qq422016 qtio422016.Writer, id string, chart C3Chart) {
	//line chart_html_simple.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line chart_html_simple.qtpl:6
	StreamC3ChartHtmlSimple(qw422016, id, chart)
	//line chart_html_simple.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line chart_html_simple.qtpl:6
}

//line chart_html_simple.qtpl:6
func C3ChartHtmlSimple(id string, chart C3Chart) string {
	//line chart_html_simple.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
	//line chart_html_simple.qtpl:6
	WriteC3ChartHtmlSimple(qb422016, id, chart)
	//line chart_html_simple.qtpl:6
	qs422016 := string(qb422016.B)
	//line chart_html_simple.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
	//line chart_html_simple.qtpl:6
	return qs422016
//line chart_html_simple.qtpl:6
}
