// Code generated by qtc from "template_bar.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template_bar.qtpl:1
package c3

//line template_bar.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template_bar.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template_bar.qtpl:1
func StreamC3BarChartJS(qw422016 *qt422016.Writer, chart C3Chart) {
//line template_bar.qtpl:1
	qw422016.N().S(`
c3.generate({
    data: `)
//line template_bar.qtpl:3
	qw422016.N().Z(chart.Data.MustJSON())
//line template_bar.qtpl:3
	qw422016.N().S(`,
    bar: {
        `)
//line template_bar.qtpl:5
	if chart.Bar.WidthRatio > 0.0 {
//line template_bar.qtpl:5
		qw422016.N().S(`
        width: {
            ratio: `)
//line template_bar.qtpl:7
		qw422016.N().F(chart.Bar.WidthRatio)
//line template_bar.qtpl:7
		qw422016.N().S(`  // this makes bar width 50% of length between ticks
        }
        `)
//line template_bar.qtpl:9
	} else if chart.Bar.Width > 0 {
//line template_bar.qtpl:9
		qw422016.N().S(`
            width: `)
//line template_bar.qtpl:10
		qw422016.N().D(chart.Bar.Width)
//line template_bar.qtpl:10
		qw422016.N().S(` // this makes bar width 100px
        `)
//line template_bar.qtpl:11
	}
//line template_bar.qtpl:11
	qw422016.N().S(`
    }
});
`)
//line template_bar.qtpl:14
}

//line template_bar.qtpl:14
func WriteC3BarChartJS(qq422016 qtio422016.Writer, chart C3Chart) {
//line template_bar.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template_bar.qtpl:14
	StreamC3BarChartJS(qw422016, chart)
//line template_bar.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line template_bar.qtpl:14
}

//line template_bar.qtpl:14
func C3BarChartJS(chart C3Chart) string {
//line template_bar.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line template_bar.qtpl:14
	WriteC3BarChartJS(qb422016, chart)
//line template_bar.qtpl:14
	qs422016 := string(qb422016.B)
//line template_bar.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line template_bar.qtpl:14
	return qs422016
//line template_bar.qtpl:14
}
