// This file is automatically generated by qtc from "template.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package c3

//line template.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:1
func StreamC3DonutChartPage(qw422016 *qt422016.Writer, data TemplateData) {
	//line template.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.15/c3.min.js"></script>
	<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.15/c3.min.css">
</head>
<body>
	<h1>C3 Simple Example</h1>

	<input type="button" onclick="chart.transform('bar')" value="Bar" />
	<input type="button" onclick="chart.transform('pie')" value="Pie" />
	<input type="button" onclick="chart.transform('donut')" value="Donut" />

	<div id="chart"></div>

	<script>

	var chart = c3.generate(
		`)
	//line template.qtpl:21
	qw422016.N().V(string(data.FormattedDataJSON()))
	//line template.qtpl:21
	qw422016.N().S(`
	);

	</script>

</body>
</html>
`)
//line template.qtpl:28
}

//line template.qtpl:28
func WriteC3DonutChartPage(qq422016 qtio422016.Writer, data TemplateData) {
	//line template.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:28
	StreamC3DonutChartPage(qw422016, data)
	//line template.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:28
}

//line template.qtpl:28
func C3DonutChartPage(data TemplateData) string {
	//line template.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:28
	WriteC3DonutChartPage(qb422016, data)
	//line template.qtpl:28
	qs422016 := string(qb422016.B)
	//line template.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:28
	return qs422016
//line template.qtpl:28
}
