// Code generated by qtc from "columnchart.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line columnchart.qtpl:1
package columnchart

//line columnchart.qtpl:1
import "github.com/grokify/gocharts/v2/charts/google"

//line columnchart.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line columnchart.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line columnchart.qtpl:2
func StreamColumnChartMaterialPage(qw422016 *qt422016.Writer, chart google.Chart) {
//line columnchart.qtpl:2
	qw422016.N().S(`<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
  <h1>`)
//line columnchart.qtpl:8
	qw422016.N().S(chart.PageTitle())
//line columnchart.qtpl:8
	qw422016.N().S(`</h1>
  <div id="`)
//line columnchart.qtpl:9
	qw422016.N().S(chart.ChartDivOrDefault())
//line columnchart.qtpl:9
	qw422016.N().S(`"></div>
  <script>
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
      var data = google.visualization.arrayToDataTable(`)
//line columnchart.qtpl:15
	qw422016.N().Z(chart.DataTableJSON())
//line columnchart.qtpl:15
	qw422016.N().S(`);

      var view = new google.visualization.DataView(data);

      var options = `)
//line columnchart.qtpl:19
	qw422016.N().Z(chart.OptionsJSON())
//line columnchart.qtpl:19
	qw422016.N().S(`

      var chart = new google.visualization.ColumnChart(document.getElementById('`)
//line columnchart.qtpl:21
	qw422016.N().S(chart.ChartDivOrDefault())
//line columnchart.qtpl:21
	qw422016.N().S(`'));

      chart.draw(view, options);
    }
    </script>
  </body>
</html>
`)
//line columnchart.qtpl:28
}

//line columnchart.qtpl:28
func WriteColumnChartMaterialPage(qq422016 qtio422016.Writer, chart google.Chart) {
//line columnchart.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line columnchart.qtpl:28
	StreamColumnChartMaterialPage(qw422016, chart)
//line columnchart.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line columnchart.qtpl:28
}

//line columnchart.qtpl:28
func ColumnChartMaterialPage(chart google.Chart) string {
//line columnchart.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line columnchart.qtpl:28
	WriteColumnChartMaterialPage(qb422016, chart)
//line columnchart.qtpl:28
	qs422016 := string(qb422016.B)
//line columnchart.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line columnchart.qtpl:28
	return qs422016
//line columnchart.qtpl:28
}
