// Code generated by qtc from "table_simple.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line table_simple.qtpl:1
package table

//line table_simple.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line table_simple.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line table_simple.qtpl:1
func StreamSimpleTable(qw422016 *qt422016.Writer, table Table) {
//line table_simple.qtpl:1
	qw422016.N().S(`

<table id="`)
//line table_simple.qtpl:3
	qw422016.E().S(table.ID)
//line table_simple.qtpl:3
	qw422016.N().S(`" style="`)
//line table_simple.qtpl:3
	qw422016.E().S(table.Style)
//line table_simple.qtpl:3
	qw422016.N().S(`">
`)
//line table_simple.qtpl:4
	if len(table.Rows) > 0 {
//line table_simple.qtpl:4
		qw422016.N().S(`
<thead>
    `)
//line table_simple.qtpl:6
		for _, item := range table.Rows[0] {
//line table_simple.qtpl:6
			qw422016.N().S(`
        <th>`)
//line table_simple.qtpl:7
			qw422016.E().S(item)
//line table_simple.qtpl:7
			qw422016.N().S(`</th>
    `)
//line table_simple.qtpl:8
		}
//line table_simple.qtpl:8
		qw422016.N().S(`
</thead>
`)
//line table_simple.qtpl:10
	}
//line table_simple.qtpl:10
	qw422016.N().S(`
`)
//line table_simple.qtpl:11
	if len(table.Rows) > 1 {
//line table_simple.qtpl:11
		qw422016.N().S(`
<tbody>
`)
//line table_simple.qtpl:13
		for _, r := range table.Rows[1:] {
//line table_simple.qtpl:13
			qw422016.N().S(`
    <tr>
    `)
//line table_simple.qtpl:15
			for _, item := range r {
//line table_simple.qtpl:15
				qw422016.N().S(`
        <td>`)
//line table_simple.qtpl:16
				qw422016.E().S(item)
//line table_simple.qtpl:16
				qw422016.N().S(`</td>
    `)
//line table_simple.qtpl:17
			}
//line table_simple.qtpl:17
			qw422016.N().S(`
    </tr>
`)
//line table_simple.qtpl:19
		}
//line table_simple.qtpl:19
		qw422016.N().S(`
</tbody>
`)
//line table_simple.qtpl:21
	}
//line table_simple.qtpl:21
	qw422016.N().S(`
</table>

`)
//line table_simple.qtpl:24
}

//line table_simple.qtpl:24
func WriteSimpleTable(qq422016 qtio422016.Writer, table Table) {
//line table_simple.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line table_simple.qtpl:24
	StreamSimpleTable(qw422016, table)
//line table_simple.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line table_simple.qtpl:24
}

//line table_simple.qtpl:24
func SimpleTable(table Table) string {
//line table_simple.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line table_simple.qtpl:24
	WriteSimpleTable(qb422016, table)
//line table_simple.qtpl:24
	qs422016 := string(qb422016.B)
//line table_simple.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line table_simple.qtpl:24
	return qs422016
//line table_simple.qtpl:24
}
