on: [push, pull_request]
name: lint

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.18.x, 1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.41
